site_name: rLLM
site_description: A library for training LLM agents with reinforcement learning
repo_url: https://github.com/agentica-project/rllm
theme:
  name: material
  logo: assets/agentica-logo.png
  favicon: assets/agentica-logo.png
  palette:
    primary: black
    accent: black
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ['.', '..']
      check_paths: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quick-start.md
  - Core Concepts:
      - Agent and Environment: core-concepts/agent_env.md
      - AgentExecutionEngine for Trajectory Rollout: core-concepts/execution-engine.md
      - AgentTrainer for RL Training: core-concepts/training.md
      - RL Algorithms for Agents: core-concepts/rl-algos.md
  - Examples:
      - Overview: examples/index.md
      - DeepSWE Agent: examples/swe.md
      - DeepScaleR: examples/deepscaler.md
      - DeepCoder: examples/deepcoder.md
      - Search Agent: examples/search.md
      - FrozenLake Agent: examples/frozenlake.md
      - WebAgent with BrowserGym: examples/web.md

  - API Reference:
      - Agents: api/agents.md
      - Environments: api/environments.md
  - Contributing: contributing.md
